stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  script:
    - node .
  artifacts:
    paths:
      - bookmark

deploy:
  stage: deploy
  script:
   - ls
   - mkdir .deploy
   - cd .deploy
   - git config --global user.email "sharvan.bhatt@gmail.com"
   - git config --global user.name "Sharvan Bhatt"
   - git clone https://github.com/sbhatt/api-pub.git
   - cd api-pub
   - git rm -r -f *
   - cd ..
   - cd ..
   - cp -r bookmark .deploy/api-pub
   - cd .deploy/api-pub/
   - git status
   - git add -A
   - git commit -m "updated Index.json" *
   - git status
   - echo $GITHUB_DEV_KEY
   - git push https://sbhatt:$GITHUB_DEV_KEY@github.com/sbhatt/api-pub.git master
   - git status
